#
# This file is meant for developers that want to run Platform 6 on their local machine
#
version: '3'

volumes:
  psql:
  parityinstance:
  demobc:

services:

  pgsql:
    container_name: pgsql
    image: postgres:9.6.1
    volumes:
      - psql:/opt/psql.data
    environment:
      - PGDATA=/opt/psql.data
    ports:
      - "5432:5432"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "b2box", "-U", "b2box", "-q"]
      interval: 1s
      timeout: 3s
      retries: 30

  p6core:
    container_name: p6core
    image: amalto/platform6:latest
    depends_on:
      - pgsql
      - parity
    volumes:
      - c:/p6core.data:/opt/b2box5.data
    links:
      - pgsql:database
    ports:
      - "8080:8080"
      - "2222:2222"
      - "5005:5005"
      - "5900:5900"
    networks:
      - app_net
    environment:
      - S6_KILL_GRACETIME=300000
      - XMX=3g

  parity:
    container_name: parity
    image: parity/parity:stable
    command:
      --config /opt/parityconf/p6instance.toml
      --jsonrpc-interface all
      --allow-ips=public
      --no-discovery
    volumes:
      - c:/p6core.data/parity/conf/:/opt/parityconf
      - parityinstance:/root/.local/share/io.parity.ethereum
    ports:
      - 8545:8545
    networks:
      app_net:
        ipv4_address: 172.13.0.10

  ethstats:
    container_name: ethstats
    image: buythewhale/ethstats_monitor
    depends_on:
      - parity
    volumes:
      - c:/p6core.data/parity/conf/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      app_net:
        ipv4_address: 172.13.0.100

  # Only for testing on a local machine, you don't need this container in production
  p6proxy:
    container_name: p6proxy
    image: amalto/b2proxy
    depends_on:
      - p6core
    environment:
      - PROXY_PLAIN_PORT=8480
      - LOG_FORMAT=string
      - LOG_LEVEL=3
      - PROXY_NO_SSL=true
      - PROXY_NO_CACHE=true
    links:
      - p6core:b2box
    ports:
      - "8480:8480"
    networks:
      - app_net

  # Local Ethereum blockchain used by the Demo App, delete this container in production
  demobc:
    container_name: demobc
    image: pegasyseng/pantheon:latest
    command:
      --network=dev
      --rpc-http-enabled
      --rpc-ws-enabled
      --host-whitelist="all"
      --rpc-http-cors-origins="all"
      --miner-enabled
      --miner-coinbase fe3b557e8fb62b89f4916b721be55ceb828dbd73
    ports:
      - "9545:8545"
    volumes:
      - demobc:/var/lib/pantheon
    networks:
      app_net:
        ipv4_address: 172.13.0.20

  # Light Ethereum blockchain explorer used by the Demo App, delete this container in production
  #demoexplorer:
  #  container_name: demoexplorer
  #  image: alethio/ethstats-lite-explorer
  #  environment:
  #    - NODE_URL='http://172.13.0.20:8545'
  #  ports:
  #    - "80:80"
  #  networks:
  #    app_net:
  #      ipv4_address: 172.13.0.200

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.13.0.0/24
