#
# This file is meant for developers that want to run Platform 6 on their local machine
#
version: '3'

services:

  pgsql:
    container_name: pgsql
    image: postgres:9.6.1
    volumes:
     - $INSTANCE_DATA_PATH/psql.data:/opt/psql.data
    environment:
     - PGDATA=/opt/psql.data
    ports:
     - "5432:5432"
    networks:
     - app_net
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "b2box", "-U", "b2box", "-q"]
      interval: 1s
      timeout: 3s
      retries: 30

  platform6:
    container_name: platform6
    image: amalto/platform6:latest
    depends_on:
      - pgsql
      - parity
    volumes:
     - $INSTANCE_DATA_PATH/p6core.data:/opt/b2box5.data
    links:
     - pgsql:database
    ports:
     - "8080:8080"
     - "2222:2222"
     - "5005:5005"
     - "5900:5900"
    networks:
     - app_net
    environment:
     - S6_KILL_GRACETIME=300000
     - XMX=3g
    
  parity:
    container_name: parity
    image: parity/parity:stable
    command:
      --config /opt/parityconf/p6instance.toml
      --jsonrpc-interface all
      --allow-ips=public
      --no-discovery
    volumes:
      - $INSTANCE_DATA_PATH/p6core.data/parity/conf/:/opt/parityconf
      - $INSTANCE_DATA_PATH/p6core.data/parity/instance:/root/.local/share/io.parity.ethereum/
    ports:
      - 8545:8545
    networks:
      app_net:
        ipv4_address: 172.13.0.10

  ethstats:
    container_name: ethstats
    image: buythewhale/ethstats_monitor
    depends_on:
      - parity
    volumes:
      - $INSTANCE_DATA_PATH/p6core.data/parity/conf/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      app_net:
        ipv4_address: 172.13.0.100

  p6proxy:
    container_name: p6proxy
    image: amalto/b2proxy
    depends_on:
      - platform6
    environment:
     - PROXY_PLAIN_PORT=8480
     - LOG_FORMAT=string
     - LOG_LEVEL=3
     - PROXY_NO_SSL=true
     - PROXY_NO_CACHE=true
    links:
     - platform6:b2box
    ports:
     - "8480:8480"
    networks:
     - app_net
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8480"]
        interval: 5s
        timeout: 2s
        retries: 20

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/24
